# -*- coding: utf-8 -*-
"""mdn_bank project portofolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VeJ5VzqypSsjj1cd-RgGfffl-6RnzBaO
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import glob

# Ambil semua file csv di folder
files = glob.glob("*.csv")

# Baca semua file
dfs = [pd.read_csv(f) for f in files]

# Gabungkan jadi satu DataFrame
df_all = pd.concat(dfs, ignore_index=True)

import pandas as pd
import glob

# Fungsi umum untuk cleaning
def clean_dataframe(df):
    # 1. Standardisasi nama kolom
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

    # 2. Hapus duplikasi
    df = df.drop_duplicates()

    # 3. Tangani missing values
    for col in df.columns:
        if df[col].dtype == "object":
            df[col] = df[col].fillna("Unknown").str.strip()
        else:
            df[col] = pd.to_numeric(df[col], errors="coerce")
            df[col] = df[col].fillna(0)

    # 4. Konversi kolom tanggal jika ada
    for col in df.columns:
        if "tanggal" in col or "tgl" in col:
            df[col] = pd.to_datetime(df[col], errors="coerce")

    return df

# Membaca semua file CSV
file_paths = [
    "transaksi.csv",
    "rekening.csv",
    "kredit.csv",
    "kpi_cabang.csv",
    "cabang.csv",
    "karyawan.csv",
    "nasabah.csv",
    "produk.csv"
]

cleaned_data = {}

for file in file_paths:
    try:
        df = pd.read_csv(file)
        df_clean = clean_dataframe(df)
        cleaned_data[file] = df_clean
        print(f"{file} cleaned: {df_clean.shape[0]} rows, {df_clean.shape[1]} cols")
    except Exception as e:
        print(f"Error processing {file}: {e}")

# Contoh akses hasil cleaning
rekening_clean = cleaned_data["rekening.csv"]
print(rekening_clean.head())

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Contoh: ambil hasil cleaning dari rekening.csv
df = cleaned_data["rekening.csv"]

# 1. Info & Deskripsi
print(df.info())
print(df.describe())

# 2. Distribusi saldo
sns.histplot(df["saldo"], bins=30, kde=True)
plt.title("Distribusi Saldo Rekening")
plt.show()

# 3. Status rekening
sns.countplot(x="status_rekening", data=df)
plt.title("Frekuensi Status Rekening")
plt.show()

# 4. Korelasi numerik
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Heatmap Korelasi")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load data (asumsi sudah cleaned)
nasabah = cleaned_data["nasabah.csv"]
rekening = cleaned_data["rekening.csv"]

# Join nasabah dengan rekening
df_nasabah_rek = pd.merge(nasabah, rekening, on="id_nasabah", how="inner")

# Distribusi saldo per segmen nasabah
sns.boxplot(x="segmen_nasabah", y="saldo", data=df_nasabah_rek)
plt.title("Distribusi Saldo per Segmen Nasabah")
plt.show()

"""
TAHAP 3 - PYTHON: EKSPLORASI & ANALISIS DATA
Bank Mitra Dana Nusantara | Jalankan di Google Colab
"""
import pandas as pd

print("=" * 60)
print("  EKSPLORASI DATA - BANK MITRA DANA NUSANTARA")
print("=" * 60)

# Gunakan hasil cleaning dari script sebelumnya
data = cleaned_data   # langsung pakai dictionary hasil cleaning

print("\n📋 RINGKASAN TABEL:")
for t, df in sorted(data.items()):
    print(f"  {t:20s}: {len(df):>5} baris x {len(df.columns):>2} kolom")

# --- NASABAH ---
nasabah = data["nasabah.csv"]
print("\n📊 STATISTIK NASABAH:")
print(nasabah[["usia","penghasilan_bulanan","skor_kredit"]].describe().round(0))
print("\n🏷️  Segmen:")
print(nasabah["segmen_nasabah"].value_counts())
print("\n💼 Top 5 Pekerjaan:")
print(nasabah["pekerjaan"].value_counts().head())

# --- REKENING ---
rekening = data["rekening.csv"]
aktif = rekening[rekening["status_rekening"]=="Aktif"].copy()
print(f"\n💰 REKENING AKTIF: {len(aktif):,}")
print(f"  Total Saldo : Rp {aktif['saldo'].sum():>20,.0f}")
print(f"  Rata-rata   : Rp {aktif['saldo'].mean():>20,.0f}")
aktif["kategori_saldo"] = pd.cut(
    aktif["saldo"],
    bins=[0,1e6,10e6,50e6,100e6,float("inf")],
    labels=["<1jt","1-10jt","10-50jt","50-100jt",">100jt"]
)
print("\n  Distribusi Saldo:")
print(aktif["kategori_saldo"].value_counts().sort_index())

# --- TRANSAKSI ---
trx = data["transaksi.csv"]
trx["tanggal"] = pd.to_datetime(trx["tanggal"], errors="coerce")
berhasil = trx[trx["status"]=="Berhasil"]
print(f"\n💳 TRANSAKSI: {len(trx):,} | Berhasil: {len(berhasil):,}")
print(f"  Nilai total : Rp {berhasil['nominal'].sum():>20,.0f}")
print("\n  Per Channel:")
print(trx.groupby("channel")["id_transaksi"].count().sort_values(ascending=False))
fraud = trx[trx["flag_fraud"]=="Ya"]
print(f"\n  ⚠️  Terindikasi Fraud: {len(fraud)} transaksi | Nilai: Rp {fraud['nominal'].sum():,.0f}")

# --- KREDIT ---
kredit = data["kredit.csv"]
npl = kredit[kredit["kolektibilitas"].isin(["Kurang Lancar","Diragukan","Macet"])]
npl_pct = npl["sisa_pokok"].sum() / kredit["sisa_pokok"].sum() * 100
print(f"\n🏦 KREDIT: {len(kredit)} debitur")
print(f"  Total Plafon    : Rp {kredit['plafon'].sum():,.0f}")
print(f"  ⚠️  NPL Gross   : {npl_pct:.2f}%")
print("\n  Per Kolektibilitas:")
print(kredit.groupby("kolektibilitas")["id_kredit"].count())

print("\n✅ Eksplorasi selesai!")

"""
TAHAP 3 — PYTHON: PANDAS LANJUTAN
Bank MDN | Teknik pandas yang sering dipakai BA bank
Jalankan di Google Colab
"""
import pandas as pd
import numpy as np

print("=" * 60)
print("  PANDAS LANJUTAN - BANK MDN")
print("=" * 60)

# Gunakan hasil cleaning dari dictionary cleaned_data
nasabah  = cleaned_data["nasabah.csv"]
rekening = cleaned_data["rekening.csv"]
trx      = cleaned_data["transaksi.csv"]
kredit   = cleaned_data["kredit.csv"]
kpi      = cleaned_data["kpi_cabang.csv"]

# ── 1. pivot_table ───────────────────────────────────────────
print("\n📊 1. PIVOT TABLE — Saldo per Segmen x Produk:")
rek_ns = rekening.merge(nasabah[["id_nasabah","segmen_nasabah"]], on="id_nasabah", how="left")
pivot = rek_ns.pivot_table(
    values="saldo", index="segmen_nasabah", columns="kode_produk",
    aggfunc="sum", fill_value=0
) / 1e6
print(pivot.round(0).to_string())

# ── 2. resample (time series) ────────────────────────────────
print("\n📈 2. TREN BULANAN TRANSAKSI:")
trx["tanggal"] = pd.to_datetime(trx["tanggal"], errors="coerce")
bulanan = trx[trx["status"]=="Berhasil"].set_index("tanggal").resample("ME")["nominal"].agg(["count","sum"])
bulanan.columns = ["volume","nilai"]
bulanan["nilai_m"] = bulanan["nilai"] / 1e6
print(bulanan[["volume","nilai_m"]].tail(6).round(0).to_string())

# ── 3. apply + lambda ────────────────────────────────────────
print("\n🏷️  3. KLASIFIKASI NASABAH:")
nasabah["kategori_penghasilan"] = nasabah["penghasilan_bulanan"].apply(
    lambda x: "Tinggi" if x >= 25e6 else ("Menengah" if x >= 10e6 else "Rendah")
)
print(nasabah["kategori_penghasilan"].value_counts())

# ── 4. merge lanjutan ────────────────────────────────────────
print("\n🔗 4. PROFIL LENGKAP TOP DEBITUR:")
top = kredit.sort_values("plafon", ascending=False).head(5)
top = top.merge(nasabah[["id_nasabah","nama_lengkap","segmen_nasabah"]], on="id_nasabah")
print(top[["nama_lengkap","jenis_kredit","plafon","kolektibilitas","segmen_nasabah"]].to_string(index=False))

# ── 5. groupby transform ─────────────────────────────────────
print("\n📋 5. KONTRIBUSI NASABAH DALAM SEGMENNYA:")
rek_ns["seg_total"] = rek_ns.groupby("segmen_nasabah")["saldo"].transform("sum")
rek_ns["kontribusi_pct"] = (rek_ns["saldo"] / rek_ns["seg_total"] * 100).round(2)
print(rek_ns.groupby("segmen_nasabah").agg(
    total_nasabah=("id_nasabah","nunique"),
    total_saldo=("saldo","sum"),
    avg_saldo=("saldo","mean"),
    top_kontribusi=("kontribusi_pct","max")
).round(0).to_string())

print("\n✅ Pandas lanjutan selesai!")

"""
TAHAP 4 - CUSTOMER SEGMENTATION (RFM Analysis)
Bank MDN | Program Premier & Prioritas
Jalankan di Google Colab
"""
import pandas as pd
import numpy as np

print("=" * 60)
print("  CUSTOMER SEGMENTATION - BANK MDN")
print("=" * 60)

# Gunakan hasil cleaning dari dictionary cleaned_data
nasabah   = cleaned_data["nasabah.csv"]
rekening  = cleaned_data["rekening.csv"]
transaksi = cleaned_data["transaksi.csv"]

# ── Saldo per nasabah ─────────────────────────────────────────
saldo = rekening[rekening["status_rekening"]=="Aktif"].groupby("id_nasabah")["saldo"].sum().reset_index()
saldo.columns = ["id_nasabah","total_saldo"]

# ── RFM ──────────────────────────────────────────────────────
transaksi["tanggal"] = pd.to_datetime(transaksi["tanggal"], errors="coerce")
ref = pd.Timestamp("2024-07-01")
rfm = transaksi[transaksi["status"]=="Berhasil"].groupby("id_nasabah").agg(
    last_trx=("tanggal","max"),
    frekuensi=("id_transaksi","count"),
    monetary=("nominal","sum")
).reset_index()
rfm["recency"] = (ref - rfm["last_trx"]).dt.days

# ── Gabung ───────────────────────────────────────────────────
profil = nasabah.merge(saldo, on="id_nasabah", how="left")
profil = profil.merge(rfm[["id_nasabah","recency","frekuensi","monetary"]], on="id_nasabah", how="left")
profil.fillna({"total_saldo":0,"frekuensi":0,"monetary":0,"recency":365}, inplace=True)

# ── Scoring ──────────────────────────────────────────────────
profil["r"] = pd.cut(profil["recency"], bins=[0,30,60,90,180,9999], labels=[5,4,3,2,1]).astype(int)
profil["f"] = pd.cut(profil["frekuensi"], bins=[-1,4,9,14,19,9999], labels=[1,2,3,4,5]).astype(int)
profil["m"] = pd.cut(profil["total_saldo"], bins=[-1,1e6,10e6,50e6,100e6,9e12], labels=[1,2,3,4,5]).astype(int)
profil["rfm"] = profil["r"] + profil["f"] + profil["m"]
profil["segment"] = pd.cut(profil["rfm"], bins=[0,5,8,11,15],
    labels=["At Risk","Potential","Loyal","Champions"])

# ── Output ───────────────────────────────────────────────────
print("\n📊 HASIL SEGMENTASI RFM:")
print(profil.groupby("segment").agg(
    jumlah=("id_nasabah","count"),
    avg_saldo=("total_saldo","mean"),
    avg_frekuensi=("frekuensi","mean"),
    total_saldo=("total_saldo","sum")
).round(0).to_string())

print("\n📋 STRATEGI PER SEGMEN:")
strategies = {
    "Champions":  "MDN Premier Card + Private Banking invitation",
    "Loyal":      "Upgrade Prioritas + cross-sell deposito/reksa dana",
    "Potential":  "Edukasi produk investasi + promo referral",
    "At Risk":    "Hubungi RM, tawaran retensi, survey alasan churn"
}
for seg, act in strategies.items():
    n = len(profil[profil["segment"]==seg])
    print(f"  {seg:12s} ({n:3d} nasabah): {act}")

# Simpan hasil ke file CSV (opsional di Colab)
profil[["id_nasabah","nama_lengkap","segmen_nasabah","total_saldo","frekuensi","rfm","segment","no_telepon"]].to_csv(
    "/content/output_segmentasi_rfm.csv", index=False
)
print("\n✅ Hasil disimpan ke output_segmentasi_rfm.csv")

"""
TAHAP 4 - CREDIT RISK & NPL ANALYSIS
Bank MDN | Early Warning System
Jalankan di Google Colab
"""
import pandas as pd

print("=" * 60)
print("  NPL & CREDIT RISK ANALYSIS - BANK MDN")
print("=" * 60)

# Gunakan hasil cleaning dari dictionary cleaned_data
kredit  = cleaned_data["kredit.csv"]
nasabah = cleaned_data["nasabah.csv"]
cabang  = cleaned_data["cabang.csv"]

# Gabungkan data nasabah & cabang
df = kredit.merge(nasabah[["id_nasabah","usia","pekerjaan","penghasilan_bulanan","nama_lengkap"]],
                  on="id_nasabah", how="left")
df = df.merge(cabang[["kode_cabang","nama_cabang","kota"]], on="kode_cabang", how="left")

# Hitung NPL Gross
npl_mask = df["kolektibilitas"].isin(["Kurang Lancar","Diragukan","Macet"])
npl_pct  = df[npl_mask]["sisa_pokok"].sum() / df["sisa_pokok"].sum() * 100

print(f"\n📊 PORTFOLIO OVERVIEW:")
print(f"  Total Debitur  : {len(df):,}")
print(f"  Total Plafon   : Rp {df['plafon'].sum()/1e12:.2f} Triliun")
print(f"  Sisa Pokok     : Rp {df['sisa_pokok'].sum()/1e12:.2f} Triliun")
print(f"  NPL Gross      : {npl_pct:.2f}%  {'✅ AMAN (<5%)' if npl_pct<5 else '❌ ALERT!'}")

# NPL per Jenis Kredit
print("\n📋 NPL per Jenis Kredit:")
for jk in df["jenis_kredit"].unique():
    sub = df[df["jenis_kredit"]==jk]
    n = sub[sub["kolektibilitas"].isin(["Kurang Lancar","Diragukan","Macet"])]["sisa_pokok"].sum()
    pct = n / sub["sisa_pokok"].sum() * 100
    print(f"  {jk:20s}: NPL {pct:.2f}%  ({len(sub)} debitur)")

# Early Warning System
print("\n🚨 EARLY WARNING - Debitur DPD≥1 dengan Sisa Pokok >50 Juta:")
ew = df[(df["bucket_dpd"]>=1) & (df["sisa_pokok"]>50e6)].sort_values("sisa_pokok", ascending=False)
print(f"  Ditemukan: {len(ew)} debitur")
if len(ew):
    print(ew[["id_kredit","nama_lengkap","jenis_kredit","sisa_pokok","kolektibilitas","nama_cabang"]].head(8).to_string(index=False))

# Top 5 Cabang dengan NPL tertinggi
print("\n🏦 TOP 5 CABANG NPL TERTINGGI:")
npl_cb = df.groupby("nama_cabang").apply(lambda x: pd.Series({
    "debitur": len(x),
    "sisa_pokok": x["sisa_pokok"].sum(),
    "npl_pct": x[x["kolektibilitas"].isin(["Kurang Lancar","Diragukan","Macet"])]["sisa_pokok"].sum()/x["sisa_pokok"].sum()*100
})).round(2).sort_values("npl_pct", ascending=False)
print(npl_cb.head(5).to_string())

print("\n✅ Analisis kredit selesai!")

"""
TAHAP 4 - BRANCH PERFORMANCE SCORECARD
Bank MDN | Monthly Performance Review H1 2024
Jalankan di Google Colab
"""
import pandas as pd
import numpy as np

print("=" * 60)
print("  BRANCH PERFORMANCE SCORECARD - H1 2024")
print("  Bank Mitra Dana Nusantara")
print("=" * 60)

# Gunakan hasil cleaning dari dictionary cleaned_data
kpi = cleaned_data["kpi_cabang.csv"]

# Filter H1 2024
h1 = kpi[kpi["tahun"]==2024]
sc = h1.groupby(["kode_cabang","nama_cabang"]).agg(
    total_dpk=("dana_pihak_ketiga","sum"),
    avg_npl=("npl_pct","mean"),
    total_fee=("fee_based_income","sum"),
    total_nsb=("nasabah_baru","sum"),
    avg_pct=("pencapaian_pct","mean")
).reset_index()

# Fungsi scoring
def pct_score(s, asc=True):
    r = s.rank(pct=True)
    return (np.ceil((r if asc else 1-r)*5).clip(1,5)).astype(int)

# Hitung skor per indikator
sc["s_dpk"] = pct_score(sc["total_dpk"])
sc["s_npl"] = pct_score(sc["avg_npl"], asc=False)
sc["s_fee"] = pct_score(sc["total_fee"])
sc["s_nsb"] = pct_score(sc["total_nsb"])
sc["s_pct"] = pct_score(sc["avg_pct"])

# Skor akhir & predikat
sc["skor"]  = (sc["s_dpk"]*0.35 + sc["s_npl"]*0.25 + sc["s_fee"]*0.20 + sc["s_nsb"]*0.10 + sc["s_pct"]*0.10).round(2)
sc["predikat"] = pd.cut(sc["skor"], bins=[0,2,3,4,5], labels=["Poor","Fair","Good","Excellent"])
sc = sc.sort_values("skor", ascending=False).reset_index(drop=True)
sc.index += 1

# Output Scorecard
print("\n🏆 SCORECARD KINERJA CABANG:")
print(f"{'Rk':>3} {'Cabang':<30} {'DPK(Rp M)':>10} {'NPL%':>6} {'Skor':>6} {'Predikat'}")
print("-"*65)
for i, r in sc.iterrows():
    print(f"{i:>3} {r.nama_cabang:<30} {r.total_dpk/1e9:>10.0f} {r.avg_npl:>6.2f} {r.skor:>6.2f} {r.predikat}")

# Ringkasan per predikat
for p in ["Excellent","Good","Fair","Poor"]:
    print(f"  {p}: {len(sc[sc['predikat']==p])} cabang")

print("\n✅ Branch scorecard selesai!")

"""
TAHAP 5 - ADVANCED ANALYTICS: FRAUD DETECTION
Bank MDN | Pattern Analysis Transaksi Mencurigakan
Jalankan di Google Colab
"""
import pandas as pd
import numpy as np
from datetime import datetime

print("=" * 60)
print("  FRAUD DETECTION ANALYSIS - BANK MDN")
print("=" * 60)

# Gunakan hasil cleaning dari dictionary cleaned_data
trx     = cleaned_data["transaksi.csv"]
nasabah = cleaned_data["nasabah.csv"]

# Preprocessing
trx["tanggal"] = pd.to_datetime(trx["tanggal"], errors="coerce")
trx["jam_int"]  = trx["jam"].str[:2].astype(int)
trx["is_fraud"] = (trx["flag_fraud"]=="Ya").astype(int)

# 1. Fraud pattern by channel
print("\n📊 FRAUD RATE per CHANNEL:")
ch = trx.groupby("channel").agg(
    total=("id_transaksi","count"),
    fraud=("is_fraud","sum"),
    avg_nominal=("nominal","mean")
).assign(fraud_rate=lambda x: (x.fraud/x.total*100).round(2))
print(ch.sort_values("fraud_rate", ascending=False).to_string())

# 2. Fraud by hour
print("\n🕐 DISTRIBUSI FRAUD per JAM:")
fraud_hour = trx[trx["is_fraud"]==1].groupby("jam_int")["id_transaksi"].count()
for h in sorted(fraud_hour.index):
    bar = "█" * int(fraud_hour[h]/fraud_hour.max()*20)
    print(f"  {h:02d}:00 | {bar:<20} {fraud_hour[h]}")

# 3. High-risk transactions
print("\n🚨 TRANSAKSI HIGH-RISK (fraud + nominal besar):")
high = trx[(trx["is_fraud"]==1) & (trx["nominal"]>10e6) & (trx["status"]=="Berhasil")]
high = high.merge(nasabah[["id_nasabah","nama_lengkap","segmen_nasabah","skor_kredit"]], on="id_nasabah", how="left")
print(high[["id_transaksi","nama_lengkap","nominal","channel","jam","tanggal","segmen_nasabah"]]
      .sort_values("nominal", ascending=False).head(10).to_string(index=False))

# 4. Nasabah dengan multiple fraud transactions
print("\n👤 NASABAH DENGAN BANYAK TRANSAKSI FRAUD:")
fraud_cnt = trx[trx["is_fraud"]==1].groupby(["id_nasabah"])["id_transaksi"].count()
fraud_cnt = fraud_cnt[fraud_cnt > 1].sort_values(ascending=False)
fraud_cnt = fraud_cnt.reset_index().merge(nasabah[["id_nasabah","nama_lengkap"]], on="id_nasabah", how="left")
print(fraud_cnt[["id_nasabah","nama_lengkap","id_transaksi"]].head(10).to_string(index=False))

# 5. Rule-based alert
print("\n⚡ ATURAN ALERT FRAUD (Rule-Based):")
alerts = []
# Rule 1: Nominal > 50 juta
r1 = trx[(trx["nominal"]>50e6) & (trx["status"]=="Berhasil")]
alerts.append(f"  Rule 1 - Nominal >50jt   : {len(r1)} transaksi")
# Rule 2: Jam 00:00-05:00
r2 = trx[(trx["jam_int"].between(0,5)) & (trx["status"]=="Berhasil")]
alerts.append(f"  Rule 2 - Dini hari 00-05 : {len(r2)} transaksi")
# Rule 3: > 5 transaksi dari 1 rekening dalam sehari
daily_cnt = trx[trx["status"]=="Berhasil"].groupby(["nomor_rekening","tanggal"])["id_transaksi"].count()
r3 = daily_cnt[daily_cnt > 5]
alerts.append(f"  Rule 3 - >5 trx/hari/rek : {len(r3)} kasus")

for a in alerts:
    print(a)

print("\n✅ Fraud detection analysis selesai!")

"""
TAHAP 5 — CHURN ANALYSIS & RETENSI NASABAH
Bank MDN | Identifikasi nasabah berisiko pindah ke bank lain
Jalankan di Google Colab
"""
import pandas as pd
import numpy as np

print("=" * 60)
print("  CHURN ANALYSIS - BANK MDN")
print("=" * 60)

# Gunakan hasil cleaning dari dictionary cleaned_data
nasabah  = cleaned_data["nasabah.csv"]
rekening = cleaned_data["rekening.csv"]
trx      = cleaned_data["transaksi.csv"]

# Preprocessing transaksi
trx["tanggal"] = pd.to_datetime(trx["tanggal"], errors="coerce")
ref_date = pd.Timestamp("2024-07-01")

# Last transaction per nasabah
last_trx = trx[trx["status"]=="Berhasil"].groupby("id_nasabah")["tanggal"].max().reset_index()
last_trx.columns = ["id_nasabah","last_trx"]
last_trx["days_since"] = (ref_date - last_trx["last_trx"]).dt.days

# Frekuensi transaksi 3 bulan terakhir
trx_3m = trx[(trx["tanggal"] >= "2024-04-01") & (trx["status"]=="Berhasil")]
freq_3m = trx_3m.groupby("id_nasabah")["id_transaksi"].count().reset_index()
freq_3m.columns = ["id_nasabah","freq_3m"]

# Saldo & rekening bermasalah
saldo = rekening[rekening["status_rekening"]=="Aktif"].groupby("id_nasabah")["saldo"].sum().reset_index()
dorm  = rekening[rekening["status_rekening"].isin(["Dormant","Ditutup"])].groupby("id_nasabah").size().reset_index()
dorm.columns = ["id_nasabah","rek_bermasalah"]

# Gabungkan semua profil
df = nasabah.merge(last_trx, on="id_nasabah", how="left")
df = df.merge(freq_3m, on="id_nasabah", how="left")
df = df.merge(saldo, on="id_nasabah", how="left")
df = df.merge(dorm, on="id_nasabah", how="left")
df.fillna({"days_since":999,"freq_3m":0,"saldo":0,"rek_bermasalah":0}, inplace=True)

# Fungsi scoring churn
def churn_score(row):
    score = 0
    if row["days_since"] > 90:   score += 40
    elif row["days_since"] > 60: score += 20
    elif row["days_since"] > 30: score += 10
    if row["freq_3m"] == 0:      score += 30
    elif row["freq_3m"] < 3:     score += 15
    if row["saldo"] < 1e6:       score += 20
    elif row["saldo"] < 5e6:     score += 10
    if row["rek_bermasalah"] > 0: score += 10
    return min(score, 100)

df["churn_score"] = df.apply(churn_score, axis=1)
df["churn_risk"]  = pd.cut(df["churn_score"], bins=[-1,30,60,80,100],
    labels=["Low","Medium","High","Critical"])

# Output distribusi risiko
print("\n📊 DISTRIBUSI RISIKO CHURN:")
print(df["churn_risk"].value_counts().to_string())

print("\n🚨 CRITICAL CHURN RISK (Top 15):")
crit = df[df["churn_risk"]=="Critical"].sort_values("churn_score", ascending=False)
print(crit[["id_nasabah","nama_lengkap","segmen_nasabah","days_since","freq_3m","saldo","churn_score","no_telepon"]].head(15).to_string(index=False))

print("\n💰 ESTIMASI DANA BERISIKO:")
for risk in ["Critical","High","Medium"]:
    s = df[df["churn_risk"]==risk]
    print(f"  {risk:10s}: {len(s):3d} nasabah | Dana: Rp {s['saldo'].sum()/1e6:,.0f} juta")

print("\n📋 STRATEGI RETENSI:")
retention = {
    "Critical": "Hubungi RM dalam 48 jam, special rate deposito, hadiah langsung",
    "High":     "WhatsApp blast promo MDN Rewards, undangan event eksklusif",
    "Medium":   "Push notification mobile banking, edukasi produk investasi",
    "Low":      "Newsletter bulanan, info produk baru"
}
for tier, strat in retention.items():
    n = len(df[df["churn_risk"]==tier])
    print(f"  {tier:10s} ({n} nasabah): {strat}")

# Simpan hasil ke file CSV (opsional di Colab)
df[["id_nasabah","nama_lengkap","segmen_nasabah","saldo","days_since","freq_3m","churn_score","churn_risk","no_telepon","email"]].to_csv(
    "/content/output_churn.csv", index=False
)
print("\n✅ Hasil disimpan ke output_churn.csv")

"""
TAHAP 5 — LOAN TREND & SIMPLE FORECAST
Bank MDN | Proyeksi DPK untuk perencanaan bisnis 2025
Jalankan di Google Colab
"""
import pandas as pd
import numpy as np

print("=" * 60)
print("  TREND ANALYSIS & FORECAST - BANK MDN")
print("=" * 60)

# Gunakan hasil cleaning dari dictionary cleaned_data
kpi = cleaned_data["kpi_cabang.csv"]

# Agregasi bulanan
monthly = kpi.groupby(["tahun","bulan"]).agg(
    dpk=("dana_pihak_ketiga","sum"),
    kredit=("kredit_outstanding","sum"),
    npl=("npl_pct","mean"),
    fee=("fee_based_income","sum"),
    nsb_baru=("nasabah_baru","sum")
).reset_index()

monthly["periode"] = monthly["tahun"].astype(str)+"-"+monthly["bulan"].astype(str).str.zfill(2)
monthly["t"] = range(len(monthly))

# Output tren bulanan
print("\n📊 TREN BULANAN:")
print(f"{'Periode':<10} {'DPK (Rp M)':>12} {'LDR%':>7} {'NPL%':>7} {'NSB Baru':>9}")
print("-"*50)
for _, r in monthly.iterrows():
    ldr = r.kredit/r.dpk*100 if r.dpk > 0 else 0
    print(f"{r.periode:<10} {r.dpk/1e9:>12.1f} {ldr:>7.1f} {r.npl:>7.2f} {r.nsb_baru:>9.0f}")

# Pertumbuhan bulanan
monthly["dpk_growth"] = monthly["dpk"].pct_change()*100
print("\n📈 RATA-RATA PERTUMBUHAN BULANAN:")
for yr in monthly["tahun"].unique():
    s = monthly[monthly["tahun"]==yr]
    print(f"  {yr}: DPK {s['dpk_growth'].mean():+.2f}%/bln")

# Fungsi forecast linear sederhana
def linear_forecast(series, n=6):
    x = np.arange(len(series))
    y = series.values
    slope = (len(x)*np.sum(x*y) - np.sum(x)*np.sum(y)) / (len(x)*np.sum(x**2) - np.sum(x)**2)
    intercept = (np.sum(y) - slope*np.sum(x)) / len(x)
    return slope * np.arange(len(series), len(series)+n) + intercept

# Forecast H2 2024
fc = linear_forecast(monthly["dpk"], n=6)
print("\n🔮 PROYEKSI DPK H2 2024 (Linear Trend):")
months_id = ["Jul","Ags","Sep","Okt","Nov","Des"]
base = monthly["dpk"].iloc[-1]
for mo, v in zip(months_id, fc):
    g = (v-base)/base*100
    print(f"  2024-{mo}: Rp {v/1e9:8.1f} M  ({'▲' if g>0 else '▼'} {abs(g):.1f}%)")

# Target skenario 2025
print("\n📋 SKENARIO TARGET 2025:")
for pct in [5,10,15]:
    t = base*(1+pct/100)
    print(f"  Target +{pct}%: Rp {t/1e9:.1f} M  | Tambahan: Rp {(t-base)/1e9:.1f} M")

print("\n✅ Forecast selesai!")

"""
TAHAP 6 - REPORTING: VISUALISASI DATA (Matplotlib/Seaborn)
Bank MDN | Executive Dashboard Charts
Jalankan di Google Colab
"""
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

try:
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import seaborn as sns
    HAS_MPL = True
except ImportError:
    HAS_MPL = False
    print("⚠️  Install matplotlib & seaborn: pip install matplotlib seaborn")

# Gunakan hasil cleaning dari dictionary cleaned_data
nasabah  = cleaned_data["nasabah.csv"]
kredit   = cleaned_data["kredit.csv"]
trx      = cleaned_data["transaksi.csv"]
kpi      = cleaned_data["kpi_cabang.csv"]
rekening = cleaned_data["rekening.csv"]

print("=" * 60)
print("  VISUALISASI DATA - BANK MDN EXECUTIVE DASHBOARD")
print("=" * 60)

if not HAS_MPL:
    # Print text-based charts jika matplotlib tidak ada
    print("\n📊 TEKS-BASED CHARTS:")
    print("\n1. Distribusi Segmen Nasabah:")
    for seg, cnt in nasabah["segmen_nasabah"].value_counts().items():
        bar = "█" * (cnt//5)
        print(f"  {seg:12s}: {bar} {cnt}")

    print("\n2. NPL per Jenis Kredit:")
    for jk in kredit["jenis_kredit"].unique():
        sub = kredit[kredit["jenis_kredit"]==jk]
        npl = sub[sub["kolektibilitas"].isin(["Kurang Lancar","Diragukan","Macet"])]["sisa_pokok"].sum()
        pct = npl/sub["sisa_pokok"].sum()*100
        bar = "█" * int(pct*2)
        print(f"  {jk:20s}: {bar} {pct:.1f}%")

    print("\n3. Tren DPK 2024 (Rp Miliar):")
    h1 = kpi[kpi["tahun"]==2024].groupby("bulan")["dana_pihak_ketiga"].sum()
    for mo, val in h1.items():
        bar = "█" * int(val/1e11)
        print(f"  Bln {mo:02d}: {bar} Rp{val/1e9:.0f}M")
    print("\n  Simpan sebagai .py lalu install matplotlib untuk grafik penuh!")
else:
    plt.style.use("seaborn-v0_8-whitegrid")
    fig, axes = plt.subplots(2, 3, figsize=(18, 11))
    fig.suptitle("Bank Mitra Dana Nusantara - Executive Dashboard", fontsize=16, fontweight="bold")

    # Chart 1: Segmen nasabah
    seg = nasabah["segmen_nasabah"].value_counts()
    colors = ["#1a3a6b","#2563eb","#93c5fd"]
    axes[0,0].pie(seg.values, labels=seg.index, autopct="%1.1f%%", colors=colors, startangle=90)
    axes[0,0].set_title("Distribusi Segmen Nasabah")

    # Chart 2: DPK Trend
    trnd = kpi.groupby(["tahun","bulan"])["dana_pihak_ketiga"].sum().reset_index()
    for yr, grp in trnd.groupby("tahun"):
        axes[0,1].plot(grp["bulan"], grp["dana_pihak_ketiga"]/1e9, marker="o", label=str(yr))
    axes[0,1].set_title("Tren DPK per Bulan (Rp Miliar)")
    axes[0,1].legend(); axes[0,1].set_xlabel("Bulan")

    # Chart 3: NPL per jenis kredit
    npl_j = kredit.groupby("jenis_kredit").apply(lambda x: pd.Series({
        "npl_pct": x[x["kolektibilitas"].isin(["Kurang Lancar","Diragukan","Macet"])]["sisa_pokok"].sum()/x["sisa_pokok"].sum()*100
    }))
    npl_j["npl_pct"].plot(kind="barh", ax=axes[0,2], color="#ef4444")
    axes[0,2].axvline(x=5, color="navy", linestyle="--", label="Threshold 5%")
    axes[0,2].set_title("NPL Rate per Jenis Kredit (%)")
    axes[0,2].legend()

    # Chart 4: Distribusi saldo
    aktif = rekening[rekening["status_rekening"]=="Aktif"]
    axes[1,0].hist(aktif["saldo"]/1e6, bins=30, color="#2563eb", edgecolor="white", alpha=0.8)
    axes[1,0].set_title("Distribusi Saldo Rekening Aktif (Juta Rp)")
    axes[1,0].set_xlabel("Saldo (Juta Rp)")

    # Chart 5: Top 8 Cabang DPK
    top_cb = kpi[kpi["tahun"]==2024].groupby("nama_cabang")["dana_pihak_ketiga"].sum().nlargest(8)/1e9
    top_cb.plot(kind="bar", ax=axes[1,1], color="#1a3a6b")
    axes[1,1].set_title("Top 8 Cabang - Total DPK H1 2024 (Rp M)")
    axes[1,1].tick_params(axis="x", rotation=30)

    # Chart 6: Transaksi by channel
    trx["tanggal"] = pd.to_datetime(trx["tanggal"], errors="coerce")
    ch_cnt = trx[trx["status"]=="Berhasil"]["channel"].value_counts()
    ch_cnt.plot(kind="bar", ax=axes[1,2], color="#059669")
    axes[1,2].set_title("Volume Transaksi per Channel")
    axes[1,2].tick_params(axis="x", rotation=30)

    plt.tight_layout()
    out_path = "/content/dashboard_chart.png"  # Sesuaikan untuk Colab
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    print(f"\n✅ Chart disimpan ke: {out_path}")
    plt.show()

print("\n✅ Visualisasi selesai!")

"""
TAHAP 6 — EXECUTIVE REPORT
Bank MDN | Laporan So What? → Now What? untuk Direksi
Jalankan di Google Colab
"""
import pandas as pd
import numpy as np

print("=" * 65)
print("  EXECUTIVE REPORT — BANK MDN H1 2024")
print("=" * 65)

# Gunakan hasil cleaning dari dictionary cleaned_data
nasabah  = cleaned_data["nasabah.csv"]
kredit   = cleaned_data["kredit.csv"]
kpi      = cleaned_data["kpi_cabang.csv"]
rekening = cleaned_data["rekening.csv"]

# KPI H1 2024
h1 = kpi[kpi["tahun"]==2024]
dpk      = h1["dana_pihak_ketiga"].sum()
kredit_o = h1["kredit_outstanding"].sum()
npl_avg  = h1["npl_pct"].mean()
fee      = h1["fee_based_income"].sum()
nsb_baru = int(h1["nasabah_baru"].sum())
ldr      = kredit_o/dpk*100 if dpk > 0 else 0
target   = h1["target_dpk"].sum()
pencapaian = dpk/target*100 if target > 0 else 0

# NPL & saldo
npl_nom  = kredit[kredit["kolektibilitas"].isin(["Kurang Lancar","Diragukan","Macet"])]["sisa_pokok"].sum()
npl_pct  = npl_nom/kredit["sisa_pokok"].sum()*100
total_saldo = rekening[rekening["status_rekening"]=="Aktif"]["saldo"].sum()

# Ringkasan kinerja
print(f"""
┌──────────────────────────────────────────────────────────┐
│         RINGKASAN KINERJA BANK MDN — H1 2024             │
├──────────────────────────┬───────────────────────────────┤
│  Dana Pihak Ketiga       │  Rp {dpk/1e12:.2f} Triliun           │
│  Pencapaian Target DPK   │  {pencapaian:.1f}%  {'✅' if pencapaian>=100 else '⚠️ Bawah target'}         │
│  LDR                     │  {ldr:.1f}%  {'✅ Sehat' if 78<=ldr<=92 else '⚠️'}              │
│  NPL Gross               │  {npl_pct:.2f}%  {'✅ AMAN' if npl_pct<5 else '❌ ALERT!'}             │
│  Fee-Based Income        │  Rp {fee/1e9:.1f} Miliar            │
│  Nasabah Baru H1         │  {nsb_baru:,} nasabah                │
│  Total Saldo Rekening    │  Rp {total_saldo/1e12:.2f} Triliun           │
└──────────────────────────┴───────────────────────────────┘""")

# Temuan utama
print("\n📌 TEMUAN UTAMA (So What?):")
findings = [
    f"1. DPK {'✅ CAPAI' if pencapaian>=100 else '⚠️ BELUM CAPAI'} target ({pencapaian:.1f}%) — {'Pertahankan momentum' if pencapaian>=100 else 'Akselerasi H2 diperlukan'}",
    f"2. NPL {npl_pct:.2f}% — {'aman <5%' if npl_pct<5 else 'LAMPAUI 5% OJK, eskalasi segera'}",
    f"3. {nsb_baru:,} nasabah baru — on-track target tahunan jika H2 konsisten",
    f"4. LDR {ldr:.1f}% — {'ruang kredit masih ada' if ldr<78 else 'dalam range sehat' if ldr<=92 else 'perlu jaga likuiditas'}"
]
for f in findings:
    print(f"  {f}")

# Rekomendasi aksi
print("\n🎯 REKOMENDASI AKSI (Now What?):")
actions = [
    ("1","Intensifikasi deposito Agustus","Promo rate +0.5% untuk penempatan baru ≥Rp50jt"),
    ("2","Task force NPL KKB & KUR","Restrukturisasi 29 debitur DPD≥1, target NPL <5% akhir tahun"),
    ("3","Aktivasi 198 nasabah At Risk","Gift voucher + kunjungan RM dalam 2 minggu"),
    ("4","Perbaiki SLA ATM","Failure rate ATM 2.25% tertinggi — jadwalkan maintenance rutin"),
    ("5","Reinforcement kredit Makassar & Manado","Kirim analis kredit senior ke cabang NPL tinggi"),
]
for n, title, detail in actions:
    print(f"\n  [{n}] {title}")
    print(f"      {detail}")

print("\n✅ Executive report selesai!")

import shutil
import os
from google.colab import files

# Buat folder khusus untuk hasil
output_dir = "/content/bank_mdn_outputs"
os.makedirs(output_dir, exist_ok=True)

# Pindahkan semua file hasil ke folder output
hasil_files = [
    "/content/output_segmentasi_rfm.csv",
    "/content/output_churn.csv",
    "/content/dashboard_chart.png"
    # Tambahkan file lain sesuai script yang sudah kamu jalankan
]

for f in hasil_files:
    if os.path.exists(f):
        shutil.copy(f, output_dir)

# Buat file ZIP
zip_path = "/content/bank_mdn_results.zip"
shutil.make_archive("/content/bank_mdn_results", 'zip', output_dir)

# Download ZIP
files.download(zip_path)